### ISSUE TITLE
New requirement geopandas>=0.7 (from PyPIPackage(attr=osmnet, version=0.1.6)) does not match already installed geopandas==0.6.3

### ISSUE THREAD

**Issue by InLaw** [cript0nauta/pynixify#35]
requirements.txt
```
affine
appdirs
#appnope
arcgis
area
argon2-cffi
#atomicwrites
attrs
autoflake
backcall
beautifulsoup4
#black
bleach
bokeh
certifi
cffi
chardet
click
click-plugins
cligj
#colorama
colorcet
cryptography
cycler
dask
datashader
datashape
decorator
defusedxml
descartes
entrypoints
feather-format
fiona
flake8
flufl.enum
geoalchemy2
geofeather
geographiclib
geojson
geojsonio
geolinks
geopandas
geopy
github3.py
googledrivedownloader
greedy
idna
imageio
importlib-metadata
ipykernel
ipython
ipython-genutils
ipywidgets
jedi
jeepney
jinja2
joblib
json5
jsonschema
jupyter-client
jupyter-core
jupyterlab
jupyterlab-server
jwcrypto
keyring
kiwisolver
lerc
libpysal
lidar
llvmlite
lxml
markupsafe
matplotlib
mccabe
mercantile
missingno
mistune
momepy
more-itertools
multipledispatch
munch
mypy
mypy-extensions
nbconvert
nbformat
networkx
notebook
ntlm-auth
numba
numpy
oauthlib
osm-diff-tool
osmapi
osmnet
osmpythontools
overpass
#overpy2
owslib
packaging
pandas
pandocfilters
param
parso
pathlib
pathspec
pexpect
pickleshare
pillow
pluggy
pooch
prometheus-client
prompt-toolkit
ptyprocess
py
pyarrow
pycodestyle
#pycparser
pycsw
pyct
pydal
pyflakes
pygeos
pygis
pygments
#pykerberos
pyparsing
pyproj
pyrsistent
pyshp
pysimplegui
pytest
python-dateutil
pytz
pywavelets
#pywin32
#pywin32-ctypes
#pywinpty
pywps
pyyaml
pyzmq
rasterio
rasterstats
regex
requests
#requests-kerberos
requests-ntlm
requests-oauthlib
requests-toolbelt
richdem
rio-cogeo
rsgis
scikit-image
scikit-learn
scipy
seaborn
secretstorage
send2trash
shapely
simplejson
six
snuggs
soupsieve
spatial
sqlalchemy
supermercado
terminado
testpath
threadpoolctl
tifffile
toml
toolz
tornado
tqdm
traitlets
typed-ast
typing-extensions
ujson
uritemplate
urllib3
verde
wcwidth
webencodings
werkzeug
widgetsnbextension
#winkerberos
xarray
xarray-spatial
xmltodict
zipp
```

error:
```
/nix/store/r94aa2gj4drkhfvkm2p4ab6cblb6kxlq-python3-3.7.6/lib/python3.7/asyncio/unix_events.py:878: RuntimeWarning: A loop is being detached from a child watcher with pending handlers
  RuntimeWarning)
Traceback (most recent call last):
  File "/nix/store/s7jbqin95y5af68y3jc7qz0lmj3r3wbm-python3.7-pynixify-0.1/bin/..pynixify-wrapped-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/s7jbqin95y5af68y3jc7qz0lmj3r3wbm-python3.7-pynixify-0.1/lib/python3.7/site-packages/pynixify/command.py", line 159, in main
    max_jobs=args.max_jobs,
  File "/nix/store/r94aa2gj4drkhfvkm2p4ab6cblb6kxlq-python3-3.7.6/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/nix/store/r94aa2gj4drkhfvkm2p4ab6cblb6kxlq-python3-3.7.6/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/nix/store/s7jbqin95y5af68y3jc7qz0lmj3r3wbm-python3.7-pynixify-0.1/lib/python3.7/site-packages/pynixify/command.py", line 197, in _main_async
    for req in all_requirements
  File "/nix/store/s7jbqin95y5af68y3jc7qz0lmj3r3wbm-python3.7-pynixify-0.1/lib/python3.7/site-packages/pynixify/version_chooser.py", line 113, in require
    reqs.build_requirements)
  File "/nix/store/s7jbqin95y5af68y3jc7qz0lmj3r3wbm-python3.7-pynixify-0.1/lib/python3.7/site-packages/pynixify/version_chooser.py", line 66, in require
    f'New requirement '
pynixify.exceptions.NoMatchingVersionFound: New requirement geopandas>=0.7 (from PyPIPackage(attr=osmnet, version=0.1.6)) does not match already installed geopandas==0.6.3
```

--- 

if I skip osmnet, the error is:

```
Error parsing metadata of /nix/store/vxfm6x4mryk0maw477m7bjhdy9ynw1wl-geolinks-0.2.0.tar.gz. Assuming it has no metadata.
/nix/store/r94aa2gj4drkhfvkm2p4ab6cblb6kxlq-python3-3.7.6/lib/python3.7/asyncio/unix_events.py:878: RuntimeWarning: A loop is being detached from a child watcher with pending handlers
  RuntimeWarning)
Traceback (most recent call last):
  File "/nix/store/s7jbqin95y5af68y3jc7qz0lmj3r3wbm-python3.7-pynixify-0.1/bin/..pynixify-wrapped-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/s7jbqin95y5af68y3jc7qz0lmj3r3wbm-python3.7-pynixify-0.1/lib/python3.7/site-packages/pynixify/command.py", line 159, in main
    max_jobs=args.max_jobs,
  File "/nix/store/r94aa2gj4drkhfvkm2p4ab6cblb6kxlq-python3-3.7.6/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/nix/store/r94aa2gj4drkhfvkm2p4ab6cblb6kxlq-python3-3.7.6/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/nix/store/s7jbqin95y5af68y3jc7qz0lmj3r3wbm-python3.7-pynixify-0.1/lib/python3.7/site-packages/pynixify/command.py", line 240, in _main_async
    for package in version_chooser.all_pypi_packages()
  File "/nix/store/s7jbqin95y5af68y3jc7qz0lmj3r3wbm-python3.7-pynixify-0.1/lib/python3.7/site-packages/pynixify/command.py", line 217, in write_package_expression
    meta = await package.metadata()
  File "/nix/store/s7jbqin95y5af68y3jc7qz0lmj3r3wbm-python3.7-pynixify-0.1/lib/python3.7/site-packages/pynixify/base.py", line 77, in metadata
    self.version = Version(version)
  File "/nix/store/0bngdpmsypycaqcgs4jwxvnpzvgw68sn-python3.7-packaging-20.1/lib/python3.7/site-packages/packaging/version.py", line 275, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
```

---
is it possible to print out the package which cause the error (to skip that temporarily)?

**Comment by cript0nauta** [comment]
The root cause of the geopandas error is that probably some package required before osmnet has a less strict dependency on geopandas (for example, `geopandas>=0.3` or just `geopandas`). Then, pynixify chose to use the nixpkgs version of geopandas, which won't satisfy the osmnet requirements. This is an expected bug, since pynixify parses the requirements linearly, from top to bottom. As a workaround, have two options:

- Put the package with stricter dependencies on geopandas (in this case, osmnet) first in the requirements list. This will force pynixify to use a newer version from PyPI
- Use the `nixpkgs-unstable` channel which has a newer version of geopandas matching the requirements

**Comment by cript0nauta** [comment]
The `expected string or bytes-like object` exception looks strange. In order to better know which package triggered the bug try adding `--max-jobs=1`. This will disable concurrency so the last package being processed will probably be the culprit. 

If that doesn't work, try adding a `print(package)` before this:

```
  File "/nix/store/s7jbqin95y5af68y3jc7qz0lmj3r3wbm-python3.7-pynixify-0.1/lib/python3.7/site-packages/pynixify/command.py", line 217, in write_package_expression
    meta = await package.metadata()
```

**Comment by InLaw** [comment]
--max-jobs=1 (isn't fun :-(

reagrding "print(package)"
- you mean I should change your source code at that position / reinstall package -> and run it again

**Comment by cript0nauta** [comment]
>     * you mean I should change your source code at that position / reinstall package -> and run it again

Exactly. You can either reinstall it or run `nix-shell` inside your `pynixify/` directory (where you cloned the repo, not the one generated by the tool). In the latter case, you can run the modified version inside nix-shell but use the original version outside it.

**Comment by InLaw** [comment]
where or how to get an overview of all available `nixpkgs-unstable` archives?

**Comment by InLaw** [comment]
req.txt

```
dephell
pip 
```


```
Resolving dephell
Resolving pip
Resolving aiohttp (from PyPIPackage(attr=dephell, version=0.8.3))
Resolving attrs>=19.2.0 (from PyPIPackage(attr=dephell, version=0.8.3))
Resolving cerberus>=1.3 (from PyPIPackage(attr=dephell, version=0.8.3))
Resolving certifi (from PyPIPackage(attr=dephell, version=0.8.3))
Resolving dephell-archive>=0.1.5 (from PyPIPackage(attr=dephell, version=0.8.3))
Resolving dephell-argparse>=0.1.1 (from PyPIPackage(attr=dephell, version=0.8.3))
Resolving dephell-changelogs (from PyPIPackage(attr=dephell, version=0.8.3))
Resolving dephell-discover>=0.2.6 (from PyPIPackage(attr=dephell, version=0.8.3))
Resolving dephell-licenses>=0.1.6 (from PyPIPackage(attr=dephell, version=0.8.3))
Resolving dephell-links>=0.1.4 (from PyPIPackage(attr=dephell, version=0.8.3))
Resolving dephell-markers>=1.0.0 (from PyPIPackage(attr=dephell, version=0.8.3))
Resolving dephell-pythons>=0.1.11 (from PyPIPackage(attr=dephell, version=0.8.3))
Resolving dephell-setuptools>=0.2.1 (from PyPIPackage(attr=dephell, version=0.8.3))
Resolving dephell-shells>=0.1.3 (from PyPIPackage(attr=dephell, version=0.8.3))
Resolving dephell-specifier>=0.1.7 (from PyPIPackage(attr=dephell, version=0.8.3))
Resolving dephell-venvs>=0.1.16 (from PyPIPackage(attr=dephell, version=0.8.3))
Resolving dephell-versioning (from PyPIPackage(attr=dephell, version=0.8.3))
Resolving jinja2 (from PyPIPackage(attr=dephell, version=0.8.3))
Resolving m2r (from PyPIPackage(attr=dephell, version=0.8.3))
Resolving packaging (from PyPIPackage(attr=dephell, version=0.8.3))
Resolving pip<=19.3.1,>=18.0 (from PyPIPackage(attr=dephell, version=0.8.3))
Resolving requests (from PyPIPackage(attr=dephell, version=0.8.3))
Resolving ruamel.yaml (from PyPIPackage(attr=dephell, version=0.8.3))
Resolving tomlkit (from PyPIPackage(attr=dephell, version=0.8.3))
Resolving yaspin (from PyPIPackage(attr=dephell, version=0.8.3))
/nix/store/r94aa2gj4drkhfvkm2p4ab6cblb6kxlq-python3-3.7.6/lib/python3.7/asyncio/unix_events.py:878: RuntimeWarning: A loop is being detached from a child watcher with pending handlers
  RuntimeWarning)
Traceback (most recent call last):
  File "/nix/store/s7jbqin95y5af68y3jc7qz0lmj3r3wbm-python3.7-pynixify-0.1/bin/..pynixify-wrapped-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/s7jbqin95y5af68y3jc7qz0lmj3r3wbm-python3.7-pynixify-0.1/lib/python3.7/site-packages/pynixify/command.py", line 159, in main
    max_jobs=args.max_jobs,
  File "/nix/store/r94aa2gj4drkhfvkm2p4ab6cblb6kxlq-python3-3.7.6/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/nix/store/r94aa2gj4drkhfvkm2p4ab6cblb6kxlq-python3-3.7.6/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/nix/store/s7jbqin95y5af68y3jc7qz0lmj3r3wbm-python3.7-pynixify-0.1/lib/python3.7/site-packages/pynixify/command.py", line 197, in _main_async
    for req in all_requirements
  File "/nix/store/s7jbqin95y5af68y3jc7qz0lmj3r3wbm-python3.7-pynixify-0.1/lib/python3.7/site-packages/pynixify/version_chooser.py", line 113, in require
    reqs.build_requirements)
  File "/nix/store/s7jbqin95y5af68y3jc7qz0lmj3r3wbm-python3.7-pynixify-0.1/lib/python3.7/site-packages/pynixify/version_chooser.py", line 66, in require
    f'New requirement '
pynixify.exceptions.NoMatchingVersionFound: New requirement pip<=19.3.1,>=18.0 (from PyPIPackage(attr=dephell, version=0.8.3)) does not match already installed pip==20.1.1
```

**Comment by cript0nauta** [comment]
> where or how to get an overview of all available `nixpkgs-unstable` archives?

Do you mean all nixpkgs-unstable python packages? In that case, you can run `nix-instantiate --eval --strict --json pynixify/data/pythonPackages.nix` inside pynixify's source directory. This will print a JSON with all available nixpkgs packages and their respective versions.

Keep in mind you'll need to switch to nixpkgs-unstable first. Here is a guide about how to do it: https://nixos.wiki/wiki/Nix_channels

**Comment by InLaw** [comment]
I cannot find a folder/list where all there historical archives from `nixpkgs-unstable `(revision numbers) are listetd. 
How can I know which one the last one is / when there is an issue with pkgs from the last archive/revision, how to get the revision number from the one before?

`nix-prefetch-git https://github.com/nixos/nixpkgs-channels.git refs/heads/nixos-unstable `
- shows Commit date is 2020-08-10 13:11:39 +0200 - is that what you mean as to get a newer version of geopandas?

**Comment by cript0nauta** [comment]
Um, I'm not sure I understood your question. Maybe you're referring to this site? https://channels.nix.gsc.io/nixos-unstable/README.txt / https://channels.nix.gsc.io/nixos-unstable/history

**Comment by InLaw** [comment]
on revision
"20a80c17865dedf9565b4b8b748d56dbefea2976"

geopandas fails 
```
= 6 failed, 1158 passed, 85 skipped, 1 deselected, 20 xfailed, 1 xpassed, 135 warnings, 1 error in 82.65s (0:01:22) =
builder for '/nix/store/j77v5plzy4iaa1sv57d79hciq56sj0va-python3.7-geopandas-0.8.0.drv' failed with exit code 1
cannot build derivation '/nix/store/8j4vl28vsb9dppm358ygp3zl73gkjjp7-python3-3.7.8-env.drv': 1 dependencies couldn't be built
error: --- Error --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- nix-shell
build of '/nix/store/8j4vl28vsb9dppm358ygp3zl73gkjjp7-python3-3.7.8-env.drv' failed

```

**Comment by cript0nauta** [comment]
This is a bug in nixpkgs itself. geopandas tests are failing in nixos-unstable. I'd recommend you to report an issue in nixpkgs.

As a workaround, you can always disable geopandas tests and hope it will work ok (it is the case with most libraries). To do this, you can either:

* Maintain your own nixpkgs branch as suggested here: https://github.com/cript0nauta/pynixify/issues/47#issuecomment-675857515. You would have to tweak the check phase in `pkgs/development/python-modules/geopandas/default.nix`
* Add an overlay to your nixpkgs manual. The sections "3.1.2. Install overlays via configuration lookup" and  "15.17.3.8. How to override a Python package using overlays?" of the nixpkgs manual explain how it works. I used something like this and it seems to work ok:

```nix
self: super: {
  python3 = super.python3.override {
    packageOverrides = python-self: python-super: {
      geopandas = python-super.geopandas.overridePythonAttrs (oldAttrs: {
        doCheck = false;
      });
    };
  };
}
```
