### ISSUE TITLE
Resolving xarray-spatial

### ISSUE THREAD

**Issue by InLaw** [cript0nauta/pynixify#41]
```
Resolving xarray-spatial
Resolving dask (from PyPIPackage(attr=xarray-spatial, version=0.0.8))
Resolving datashader (from PyPIPackage(attr=xarray-spatial, version=0.0.8))
Resolving numba (from PyPIPackage(attr=xarray-spatial, version=0.0.8))
Resolving numpy (from PyPIPackage(attr=xarray-spatial, version=0.0.8))
Resolving pandas (from PyPIPackage(attr=xarray-spatial, version=0.0.8))
Resolving pillow (from PyPIPackage(attr=xarray-spatial, version=0.0.8))
Resolving requests (from PyPIPackage(attr=xarray-spatial, version=0.0.8))
Resolving scikit-learn (from PyPIPackage(attr=xarray-spatial, version=0.0.8))
Resolving scipy (from PyPIPackage(attr=xarray-spatial, version=0.0.8))
Resolving xarray (from PyPIPackage(attr=xarray-spatial, version=0.0.8))
Error parsing requirements of /nix/store/qg3j4lz94i0fs36b0g41awla3vl0sr2g-numba-0.49.1.tar.gz. Assuming it has no dependencies.
Resolving numpy>=1.15 (from NixPackage(attr=xarray, version=0.15.1))
Resolving pandas>=0.25 (from NixPackage(attr=xarray, version=0.15.1))
Resolving setuptools>=41.2 (from NixPackage(attr=xarray, version=0.15.1))
Resolving setuptools>=41.2 (from NixPackage(attr=xarray, version=0.15.1))
Resolving setuptools_scm (from NixPackage(attr=xarray, version=0.15.1))
Error parsing requirements of /nix/store/62mxgy66prigwzjwni9mb42ngqx91wx2-numpy-1.18.5.zip. Assuming it has no dependencies.
Error parsing requirements of /nix/store/j61k3mv2k4hr3qjjqxi8m348n4kkz4mp-pandas-1.0.4.tar.gz. Assuming it has no dependencies.
Resolving chardet<4,>=3.0.2 (from NixPackage(attr=requests, version=2.23.0))
Resolving idna<3,>=2.5 (from NixPackage(attr=requests, version=2.23.0))
Resolving urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from NixPackage(attr=requests, version=2.23.0))
Resolving certifi>=2017.4.17 (from NixPackage(attr=requests, version=2.23.0))
Error parsing requirements of /nix/store/axza81xvwp42v1b7lpxsrdg58vmjsrzk-scikit-learn-0.23.1.tar.gz. Assuming it has no dependencies.
Error parsing requirements of /nix/store/x11d9hxaj5jyl9myi0ariwjr824am9yk-datashader-0.11.0.tar.gz. Assuming it has no dependencies.
Error parsing requirements of /nix/store/jzrmjnhj56rdg13rqxylp3scxjjihr3v-scipy-1.4.1.tar.gz. Assuming it has no dependencies.
Resolving setuptools (from NixPackage(attr=setuptools_scm, version=4.1.2))
Error parsing requirements of /nix/store/s3rnwylp3d428whfk88dy51q2mgcahj3-setuptools-46.1.3-sdist.tar.gz. Assuming it has no dependencies.
Traceback (most recent call last):
  File "/nix/store/s7jbqin95y5af68y3jc7qz0lmj3r3wbm-python3.7-pynixify-0.1/bin/..pynixify-wrapped-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/s7jbqin95y5af68y3jc7qz0lmj3r3wbm-python3.7-pynixify-0.1/lib/python3.7/site-packages/pynixify/command.py", line 159, in main
    max_jobs=args.max_jobs,
  File "/nix/store/r94aa2gj4drkhfvkm2p4ab6cblb6kxlq-python3-3.7.6/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/nix/store/r94aa2gj4drkhfvkm2p4ab6cblb6kxlq-python3-3.7.6/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/nix/store/s7jbqin95y5af68y3jc7qz0lmj3r3wbm-python3.7-pynixify-0.1/lib/python3.7/site-packages/pynixify/command.py", line 240, in _main_async
    for package in version_chooser.all_pypi_packages()
  File "/nix/store/s7jbqin95y5af68y3jc7qz0lmj3r3wbm-python3.7-pynixify-0.1/lib/python3.7/site-packages/pynixify/command.py", line 217, in write_package_expression
    meta = await package.metadata()
  File "/nix/store/s7jbqin95y5af68y3jc7qz0lmj3r3wbm-python3.7-pynixify-0.1/lib/python3.7/site-packages/pynixify/base.py", line 77, in metadata
    self.version = Version(version)
  File "/nix/store/0bngdpmsypycaqcgs4jwxvnpzvgw68sn-python3.7-packaging-20.1/lib/python3.7/site-packages/packaging/version.py", line 275, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
```

**Comment by cript0nauta** [comment]
Here I'll track the list of packages which are working now after my fixes:

- [ ] brotli
- [ ] daiquiri
- [ ] dash
- [ ] dbt
- [ ] dictdiffer
- [ ] flask-compress
- [ ] google-crc32c
- [ ] hunter
- [ ] jq
- [ ] orange3 (orange-canvas-core/orange-widget-base)
- [ ] py-spy
- [ ] tensorflow/tensorboard-plugin-wit
- [ ] xarray-spatial

**Comment by cript0nauta** [comment]
e77dd4990a04173c99fb2098f4df7444fa1b549e fixed daiquiri, dictdiffer, google-crc32c, hunter, orange3, and xarray-spatial.

**Comment by cript0nauta** [comment]
430b63708ca625c19fb2713d876f3619c73c9cd1 fixed brotli, dash, and flask-compress.

**Comment by cript0nauta** [comment]
jq fails because it's nixpkgs expression uses `srcs` instead of `src`: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/jq/default.nix. This is technically valid, but doesn't seem to be a good practice. I would prefer to fix this in nixpkgs rather than in pynixify itself.

**Comment by InLaw** [comment]
makes sense

**Comment by cript0nauta** [comment]
dbt (actually, dbt-core) has very strict requirements: https://github.com/fishtown-analytics/dbt/blob/dev/marian-anderson/core/setup.py#L56. For example `idna<2.9` won't be compatible with the `idna` of nixpkgs, whose version is 2.9. This is an issue that has to be resolved by dbt maintainers. It should get rid of `==` and `<` requirements in order to be compatible with nixpkgs versions.

See https://github.com/cript0nauta/pynixify/#limitations for a more detailed explaination about why this is necessary.

**Comment by InLaw** [comment]
is there no way to force an overwrite of dependency versions with pynixify?

**Comment by cript0nauta** [comment]
> is there no way to force an overwrite of dependency versions with pynixify?

if you refer to overwriting the dependencies of dbt/dbt-core, there isn't a way right now.

For your own dependencies, you can as long as the dependency has a standard build process (i.e. no C code), since it won't be using the nixpkgs version of the package.

**Comment by cript0nauta** [comment]
Regarding py-spy, it only provides wheels and no source distributions. But unlike overpy2 (see #34), this library has a reason for that: it's written in Rust, so its build can be much different than normal. Because of this, automatically creating an expression for py-spy is out of pynixify's scope. In order to use it inside Nix, it should be manually included into nixpkgs first. Then, pynixify will be able to detect it and reuse its definition.

**Comment by InLaw** [comment]
ok
