### ISSUE TITLE
pkg: spacy

### ISSUE THREAD

**Issue by InLaw** [cript0nauta/pynixify#45]
spacy 
```
/nix/store/r94aa2gj4drkhfvkm2p4ab6cblb6kxlq-python3-3.7.6/lib/python3.7/asyncio/unix_events.py:878: RuntimeWarning: A loop is being detached from a child watcher with pending handlers
  RuntimeWarning)
Traceback (most recent call last):
  File "/nix/store/7ihn8710y4xjzwnc4bxqmbwy02qsbqiz-python3.7-pynixify-0.1/bin/..pynixify-wrapped-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/7ihn8710y4xjzwnc4bxqmbwy02qsbqiz-python3.7-pynixify-0.1/lib/python3.7/site-packages/pynixify/command.py", line 159, in main
    max_jobs=args.max_jobs,
  File "/nix/store/r94aa2gj4drkhfvkm2p4ab6cblb6kxlq-python3-3.7.6/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/nix/store/r94aa2gj4drkhfvkm2p4ab6cblb6kxlq-python3-3.7.6/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/nix/store/7ihn8710y4xjzwnc4bxqmbwy02qsbqiz-python3.7-pynixify-0.1/lib/python3.7/site-packages/pynixify/command.py", line 197, in _main_async
    for req in all_requirements
  File "/nix/store/7ihn8710y4xjzwnc4bxqmbwy02qsbqiz-python3.7-pynixify-0.1/lib/python3.7/site-packages/pynixify/version_chooser.py", line 113, in require
    reqs.build_requirements)
  File "/nix/store/7ihn8710y4xjzwnc4bxqmbwy02qsbqiz-python3.7-pynixify-0.1/lib/python3.7/site-packages/pynixify/version_chooser.py", line 113, in require
    reqs.build_requirements)
  File "/nix/store/7ihn8710y4xjzwnc4bxqmbwy02qsbqiz-python3.7-pynixify-0.1/lib/python3.7/site-packages/pynixify/version_chooser.py", line 66, in require
    f'New requirement '
pynixify.exceptions.NoMatchingVersionFound: New requirement wheel<0.33.0,>=0.32.0 (from NixPackage(attr=murmurhash, version=1.0.2)) does not match already installed wheel==0.33.6

```

**Comment by cript0nauta** [comment]
The problem here is caused by murmurhash. It has a strict `wheel<0.33` dependency which collides with the nixpkgs version of wheel. This has been addressed in nixpkgs by patching the requirements of murmurhash: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/murmurhash/default.nix#L17.

Unfortunately, pynixify uses the raw package source instead of applying the defined patches. This might be addressed soon, so I'll keep the issue open for now.

**Comment by InLaw** [comment]
(only out of interest)
why is 
```
postPatch = ''
    substituteInPlace setup.py --replace "'wheel>=0.32.0,<0.33.0'" ""
  '';
```

and not
```
postPatch = ''
    substituteInPlace setup.py --replace "'wheel>=0.32.0,<0.33.0'" "wheel>=0.32.0"
  '';
```

**Comment by cript0nauta** [comment]
According to the [wheel library readme](https://pypi.org/project/wheel/):

> It should be noted that wheel is not intended to be used as a library, and as such there is no stable, public API.

I guess that adding wheel as a dependency of murmurhash didn't make sense in the context of nixpkgs, so that's why the wheel dependency was removed entirely.
