### ISSUE TITLE
package: sseclient-py

### ISSUE THREAD

**Issue by JamieMagee** [cript0nauta/pynixify#51]
My guess would be that this is because sseclient-py doesn't follow semantic versioning? i.e. it's latest version is `1.7`.

```shell
Resolving sseclient-py
Traceback (most recent call last):
  File "/nix/store/vfbxgydy9np5yimzjxf028zg1gd38nnl-python3.8-pynixify-0.1/lib/python3.8/site-packages/pynixify/version_chooser.py", line 99, in require
    pkg = self._local_packages[canonicalize_name(r.name)]
KeyError: 'sseclient-py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/vfbxgydy9np5yimzjxf028zg1gd38nnl-python3.8-pynixify-0.1/bin/..pynixify-wrapped-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/vfbxgydy9np5yimzjxf028zg1gd38nnl-python3.8-pynixify-0.1/lib/python3.8/site-packages/pynixify/command.py", line 150, in main
    asyncio.run(_main_async(
  File "/nix/store/bs03sg8b0gq2zr4v252hh9psp780qj5q-python3-3.8.5/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/nix/store/bs03sg8b0gq2zr4v252hh9psp780qj5q-python3-3.8.5/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/nix/store/vfbxgydy9np5yimzjxf028zg1gd38nnl-python3.8-pynixify-0.1/lib/python3.8/site-packages/pynixify/command.py", line 195, in _main_async
    await asyncio.gather(*(
  File "/nix/store/vfbxgydy9np5yimzjxf028zg1gd38nnl-python3.8-pynixify-0.1/lib/python3.8/site-packages/pynixify/version_chooser.py", line 118, in require
    raise NoMatchingVersionFound(str(r))
pynixify.exceptions.NoMatchingVersionFound: sseclient-py
```

**Comment by cript0nauta** [comment]
Thanks for reporting! Looking at [the downloads page of the sseclient-py PyPI package](https://pypi.org/project/sseclient-py/#files), it seems that it only uploads wheel distributions (.whl) on each release. In order for the package to be usable with pynixify, it needs to upload a source distribution (.tar.gz or .zip) as most PyPI packages do. Since the package is written 100% in Python, this shouldn't be a problem. But is has to be reported to the sseclient-py maintainers instead.
